# Generated by Django 3.0.5 on 2020-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('demographic', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=20000)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
