# Generated by Django 3.0.5 on 2020-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20200514_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='img_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
